### PR TITLE
Fe editor

### PR DESCRIPTION
**Pull request by Donadonzi**
Hi Bonnie,
This is the editor branch I am working on.

### CODE REVIEW

**Comment by Donadonzi** [comment]
- Editor is working. It needs some detailed modification in the `code-block` style though.

- I set the route for fetching code from database to `/api/users/snippet`.  Do you think it's ok?

- I set up validation before submitting the code to make sure **_language_** and **_code_** are provided.

- `CodeReader `component is supposed to be able to show the fetched code properly.

**Comment by daniel-liemng** [comment]
Hi Donya,
I don't know what the icon 'Save' is for.
When the screen is the small height I don't see the title and language input, just the scroll bar like the error in the presentation

**Review by daniel-liemng — COMMENTED** [review]
What the icon "Save" is for?
The title and language input turned to scroll bar like it happened in the presentation.
When uploading to back-end. It should contain ID of author.
Everything else is good

**Comment by Donadonzi** [comment]
> What the icon "Save" is for?
> The title and language input turned to scroll bar like it happened in the presentation.
> When uploading to back-end. It should contain ID of author.
> Everything else is good

Thanks Liem. The first two issues we talked about, but I'm not sure I understand the third one. The author id is already on the `request.user._id` so it will be stored on the `author` field of the document in db.

**Comment by daniel-liemng** [comment]
I looks good now. Good job.
The third one: I checked the response in console. I didn't see author id, but when I checked DB, it was there. my bad

**Comment by Donadonzi** [comment]
> I looks good now. Good job.
> The third one: I checked the response in console. I didn't see author id, but when I checked DB, it was there. my bad

Thanks. No worries :D

**Pull request merged**
